Fix usage of `inflect()` in README
The usage of the string interpolation method `inflect()` was not
updated with the change in 8b164396, and thus none of the examples
worked as intended:

    >>> import inflect
    >>> p = inflect.engine()
    >>> word = 'leaf'
    >>>
    >>> print(p.inflect("The plural of {0} is plural({0})".format(word)))
    Traceback (most recent call last):
      ...
      File "/app/inflect/inflect.py", line 2132, in _get_value_from_ast
        raise NameError("name '%s' is not defined" % obj.id)
    NameError: name 'leaf' is not defined
    >>>
    >>> print(p.inflect("The plural of {0} is plural('{0}')".format(word)))
    The plural of leaf is leaves

This change adds single quotes (for readability) on all examples of
`infect()` in README.